### ISSUE TITLE
Only hyphen options work, arguments like `install` do not.

### ISSUE THREAD

**Issue by kir68k** [ayasa520/waydroid_script#5]
# OS Info
- Distro: openSUSE Tumbleweed 20230430
- Python: 3.10, `tqdm` & `requests` from openSUSE Factory
- Script version from HEAD

# Issue
Using instructions from the README, I can't get the script's arguments like the interactive installer to work.

In the file, it states to run the script as root without any arguments, to get the interactive installer.
I have done that, and this is my result: ![image](https://user-images.githubusercontent.com/104025732/235891966-3d07f0f7-9d29-4950-8f1e-9c55b36335f5.png)

Another example trying to use `install`: ![image](https://user-images.githubusercontent.com/104025732/236135971-e1705684-f0a5-4961-95bd-bd7715777bd1.png)

# Question
Instead of what the repo screenshots show.
Am I missing anything? I can deal with using the hyphen options, but there are are no options for `hack` or `google` this way, so it doesn't seem intentional.

**Comment by ayasa520** [comment]
I forgot to edit the README.md, so you cloned the upstream version.

**Comment by kir68k** [comment]
Oh. A bit embarrassing, first time I overlooked something like that.
